#! /bin/bash

#set -x

autorun=0
function ask()
{
	cmd="$*"
	if [ $autorun -eq 0 ]; then
		echo -n "Run '$cmd' [*y*/n/a] ? "
		read answer
	fi
	run=1
	if [ "$answer" == "a" ]; then
		autorun=1
	fi
	if [ "$answer" == "n" ]; then
		run=0
	fi
	if [ $run -eq 1 ]; then
		$cmd
		result=$?
		if [ $result -ne 0 ]; then
			echo "'$cmd' failed"
			autorun=0
			return $result;
		fi
	fi
}

cd ~/Apps/go/src
pwd
old_go=`go version`
ask nice time hg pull
ask nice time hg update release
ask nice time ./all.bash
new_go=`go version`
echo "old_go:" $old_go
echo "new_go": $new_go
