#! /bin/bash

#set -x

autorun=0
function ask()
{
	cmd="$*"
	if [ $autorun -eq 0 ]; then
		echo -n "Run '$cmd' [*y*/n/a] ? "
		read answer
	fi
	run=1
	if [ "$answer" == "a" ]; then
		autorun=1
	fi
	if [ "$answer" == "n" ]; then
		run=0
	fi
	if [ $run -eq 1 ]; then
		$cmd
		result=$?
		if [ $result -ne 0 ]; then
			echo "'$cmd' failed"
			autorun=0
			return $result;
		fi
	fi
}

cd ~/Apps/Chrome/chromium/src
pwd
ask nice time gclient sync --force
ask nice time make -j1 BUILDTYPE=Release chrome
ask nice time make -j1 chrome
ask nice time make -j1 BUILDTYPE=Release
ask nice time make -j1 
